export const LABELS = [
  "O",
  "NUM",
  "ORD",
  "UNIT",
  "DIR_BEFORE",
  "DIR_AFTER",
  "NOW",
  "REL_DAY",
  "DEICTIC",
  "WEEKDAY",
  "DAYGROUP",
  "MONTH",
  "DOM",
  "YEAR",
  "HOUR",
  "MINUTE",
  "SECOND",
  "MERIDIEM",
  "TIME_NAMED",
  "DAYPART",
  "RANGE_START",
  "RANGE_END",
  "RECUR",
  "FREQ",
  "TIMES",
  "BOUND_START",
  "BOUND_END",
  "COUNT",
  "DUR",
  "EXCEPT",
  "HOLIDAY",
  "JOIN",
  "GLUE",
  "EDGE",
  "CLOCK_OFFSET",
] as const;
export type Label = (typeof LABELS)[number];
export const labelId = /* @__PURE__ */ Object.fromEntries(
  /* @__PURE__ */ LABELS.map((name, id) => [name, id]),
) as Record<Label, number>;

/** Numeric roles stay internal; source-facing diagnostics use LABELS. */
export const enum Role {
  O = 0,
  NUM = 1,
  ORD = 2,
  UNIT = 3,
  DIR_BEFORE = 4,
  DIR_AFTER = 5,
  NOW = 6,
  REL_DAY = 7,
  DEICTIC = 8,
  WEEKDAY = 9,
  DAYGROUP = 10,
  MONTH = 11,
  DOM = 12,
  YEAR = 13,
  HOUR = 14,
  MINUTE = 15,
  SECOND = 16,
  MERIDIEM = 17,
  TIME_NAMED = 18,
  DAYPART = 19,
  RANGE_START = 20,
  RANGE_END = 21,
  RECUR = 22,
  FREQ = 23,
  TIMES = 24,
  BOUND_START = 25,
  BOUND_END = 26,
  COUNT = 27,
  DUR = 28,
  EXCEPT = 29,
  HOLIDAY = 30,
  JOIN = 31,
  GLUE = 32,
  EDGE = 33,
  CLOCK_OFFSET = 34,
}
